[package]
name = "jit"
version = "0.1.0"
edition = "2021"

[lib]
name = "jit"
path = "src/lib.rs"

[dependencies]
llvm-sys = "170"
slog = "2.7"

common = { path = "../common" }
logging = { path = "../logging" }
